author: Tobiplayer3
main: com.tobiplayer3.limitedplaytime.LimitedPlaytime
version: ${project.version}
name: LimitedPlaytime
api-version: 1.15

commands:
  playtime:
    usage: /playtime
    description: Display your playtime!
    aliases: [pt,ptime]