name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    - name: Gradle Build
      run: gradle build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: "build/libs/*.jar"